#!/bin/bash

yacc -d syntax_analyser.y 
lex lexical_analyser.l 
g++ y.tab.c lex.yy.c ./SymbolTable/SymbolTable.cpp -ll -Ly -o run
rm lex.yy.c y.tab.c y.tab.h
echo
./run < ./sample_programs/$1
rm run

cd ./ICG_QUAD
python3 ICG_Cleaner.py
cd ../

cd ./ICG_QUAD
python3 Quad_Gen.py
cd ../

cd ./CODE_OPT
python3 Code_Opt.py > OPT.txt
cd ../

echo